'use server'

import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import * as z from 'zod'
import { getSupabaseServerClient, getSupabaseAdminClient } from '@/lib/supabase/server'
import { sendInviteEmail } from '@/lib/resend'

const FREE_MEMBER_LIMIT = 2

// ── Types ─────────────────────────────────────────────────────────────────────

export type InviteActionResult = { error?: string; limitReached?: boolean }

export type WorkspaceMember = {
  userId: string
  name: string
  email: string
  role: string
  joinedAt: string
}

export type PendingInvite = {
  id: string
  email: string
  role: string
  expiresAt: string
  createdAt: string
}

// ── Helpers ───────────────────────────────────────────────────────────────────

async function getAuthedUser() {
  const supabase = await getSupabaseServerClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('Unauthorized')
  return user
}

// ── Queries ───────────────────────────────────────────────────────────────────

export async function getWorkspaceMembersWithDetails(
  workspaceId: string,
): Promise<WorkspaceMember[]> {
  await getAuthedUser()

  const admin = getSupabaseAdminClient()

  const { data: members } = await admin
    .from('workspace_members')
    .select('user_id, role, joined_at')
    .eq('workspace_id', workspaceId)
    .order('joined_at', { ascending: true })

  if (!members?.length) return []

  const { data: { users } } = await admin.auth.admin.listUsers({ perPage: 1000 })
  const userMap = new Map(users.map((u) => [u.id, u]))

  return members.map((m) => {
    const u = userMap.get(m.user_id)
    return {
      userId: m.user_id,
      name: (u?.user_metadata?.full_name as string) || u?.email || 'Usuário',
      email: u?.email || '',
      role: m.role,
      joinedAt: m.joined_at.split('T')[0],
    }
  })
}

export async function getPendingInvites(workspaceId: string): Promise<PendingInvite[]> {
  await getAuthedUser()

  const admin = getSupabaseAdminClient()
  const { data } = await admin
    .from('workspace_invites')
    .select('id, email, role, expires_at, created_at')
    .eq('workspace_id', workspaceId)
    .is('accepted_at', null)
    .gt('expires_at', new Date().toISOString())
    .order('created_at', { ascending: false })

  if (!data) return []

  return data.map((row) => ({
    id: row.id,
    email: row.email,
    role: row.role,
    expiresAt: row.expires_at,
    createdAt: row.created_at,
  }))
}

// ── Mutations ─────────────────────────────────────────────────────────────────

const InviteSchema = z.object({
  email: z.string().email('E-mail inválido'),
  role: z.enum(['admin', 'member']),
})

export async function sendInvite(
  workspaceId: string,
  formData: { email: string; role: string },
): Promise<InviteActionResult> {
  const user = await getAuthedUser()

  const parsed = InviteSchema.safeParse(formData)
  if (!parsed.success) return { error: parsed.error.issues[0].message }

  const admin = getSupabaseAdminClient()

  // Verify caller is admin of this workspace
  const { data: callerMember } = await admin
    .from('workspace_members')
    .select('role')
    .eq('workspace_id', workspaceId)
    .eq('user_id', user.id)
    .maybeSingle()
  if (callerMember?.role !== 'admin')
    return { error: 'Apenas administradores podem convidar membros.' }

  // Fetch workspace to check plan
  const { data: workspace } = await admin
    .from('workspaces')
    .select('name, plan')
    .eq('id', workspaceId)
    .single()

  if (!workspace) return { error: 'Workspace não encontrado.' }

  // Enforce Free plan member limit
  if (workspace.plan === 'free') {
    const { count } = await admin
      .from('workspace_members')
      .select('user_id', { count: 'exact', head: true })
      .eq('workspace_id', workspaceId)

    if ((count ?? 0) >= FREE_MEMBER_LIMIT) {
      return {
        error: `O plano Free permite no máximo ${FREE_MEMBER_LIMIT} membros. Faça upgrade para Pro.`,
        limitReached: true,
      }
    }
  }

  // Check if e-mail already has a pending invite
  const { data: existing } = await admin
    .from('workspace_invites')
    .select('id')
    .eq('workspace_id', workspaceId)
    .eq('email', parsed.data.email)
    .is('accepted_at', null)
    .gt('expires_at', new Date().toISOString())
    .maybeSingle()

  if (existing) return { error: 'Já existe um convite pendente para esse e-mail.' }

  // Create invite record (token generated by DB default)
  const { data: invite, error: insertError } = await admin
    .from('workspace_invites')
    .insert({
      workspace_id: workspaceId,
      email: parsed.data.email,
      role: parsed.data.role,
    })
    .select('token')
    .single()

  if (insertError || !invite) return { error: 'Erro ao criar convite.' }

  // Resolve inviter name
  const { data: { user: inviter } } = await admin.auth.admin.getUserById(user.id)
  const inviterName =
    (inviter?.user_metadata?.full_name as string) || inviter?.email || 'Alguém'

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000'
  const inviteUrl = `${appUrl}/invite/${invite.token}`

  const { error: emailError } = await sendInviteEmail({
    to: parsed.data.email,
    workspaceName: workspace.name,
    inviterName,
    role: parsed.data.role,
    inviteUrl,
  })

  if (emailError) {
    // Rollback invite if e-mail failed
    await admin.from('workspace_invites').delete().eq('token', invite.token)
    return { error: 'Erro ao enviar e-mail de convite. Tente novamente.' }
  }

  revalidatePath('/settings')
  return {}
}

export async function revokeInvite(
  workspaceId: string,
  inviteId: string,
): Promise<InviteActionResult> {
  const user = await getAuthedUser()

  const admin = getSupabaseAdminClient()

  // Verify caller is admin of this workspace
  const { data: callerMember } = await admin
    .from('workspace_members')
    .select('role')
    .eq('workspace_id', workspaceId)
    .eq('user_id', user.id)
    .maybeSingle()
  if (callerMember?.role !== 'admin')
    return { error: 'Apenas administradores podem revogar convites.' }

  const { error } = await admin
    .from('workspace_invites')
    .delete()
    .eq('id', inviteId)
    .eq('workspace_id', workspaceId)

  if (error) return { error: 'Erro ao revogar convite.' }
  revalidatePath('/settings')
  return {}
}

export async function removeMember(
  workspaceId: string,
  userId: string,
): Promise<InviteActionResult> {
  const currentUser = await getAuthedUser()
  if (currentUser.id === userId) return { error: 'Você não pode remover a si mesmo.' }

  const admin = getSupabaseAdminClient()

  // Verify caller is admin of this workspace
  const { data: callerMember } = await admin
    .from('workspace_members')
    .select('role')
    .eq('workspace_id', workspaceId)
    .eq('user_id', currentUser.id)
    .maybeSingle()

  if (callerMember?.role !== 'admin') {
    return { error: 'Apenas administradores podem remover membros.' }
  }

  // Prevent removing another admin
  const { data: targetMember } = await admin
    .from('workspace_members')
    .select('role')
    .eq('workspace_id', workspaceId)
    .eq('user_id', userId)
    .maybeSingle()

  if (targetMember?.role === 'admin') {
    return { error: 'Não é possível remover um administrador do workspace.' }
  }

  const { error } = await admin
    .from('workspace_members')
    .delete()
    .eq('workspace_id', workspaceId)
    .eq('user_id', userId)

  if (error) return { error: 'Erro ao remover membro.' }
  revalidatePath('/settings')
  return {}
}

// ── Accept invite (public, called from /invite/[token] page) ──────────────────

export async function acceptInvite(token: string): Promise<InviteActionResult> {
  const supabase = await getSupabaseServerClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    redirect(`/login?next=/invite/${token}`)
  }

  const admin = getSupabaseAdminClient()

  const { data: invite } = await admin
    .from('workspace_invites')
    .select('*')
    .eq('token', token)
    .is('accepted_at', null)
    .gt('expires_at', new Date().toISOString())
    .maybeSingle()

  if (!invite) return { error: 'Convite inválido ou expirado.' }

  // Validate that the logged-in user's email matches the invite
  if (user.email?.toLowerCase() !== invite.email.toLowerCase()) {
    return { error: 'Este convite foi enviado para outro e-mail.' }
  }

  // Check if already a member
  const { data: existing } = await admin
    .from('workspace_members')
    .select('user_id')
    .eq('workspace_id', invite.workspace_id)
    .eq('user_id', user.id)
    .maybeSingle()

  if (existing) {
    // Already a member — just mark invite as accepted and go to dashboard
    await admin
      .from('workspace_invites')
      .update({ accepted_at: new Date().toISOString() })
      .eq('token', token)
    redirect('/dashboard')
  }

  // Add to workspace
  const { error: memberError } = await admin.from('workspace_members').insert({
    workspace_id: invite.workspace_id,
    user_id: user.id,
    role: invite.role,
  })

  if (memberError) return { error: 'Erro ao ingressar no workspace.' }

  await admin
    .from('workspace_invites')
    .update({ accepted_at: new Date().toISOString() })
    .eq('token', token)

  revalidatePath('/settings')
  redirect('/dashboard')
}

// ── Token lookup (used by the accept page to render workspace info) ────────────

export type InviteDetails = {
  workspaceName: string
  role: string
  email: string
  inviterEmail: string | null
  expired: boolean
  accepted: boolean
}

export async function getInviteDetails(token: string): Promise<InviteDetails | null> {
  const admin = getSupabaseAdminClient()

  const { data: invite } = await admin
    .from('workspace_invites')
    .select('workspace_id, role, expires_at, accepted_at, email')
    .eq('token', token)
    .maybeSingle()

  if (!invite) return null

  const { data: workspace } = await admin
    .from('workspaces')
    .select('name')
    .eq('id', invite.workspace_id)
    .single()

  return {
    workspaceName: workspace?.name ?? 'Workspace',
    role: invite.role,
    email: invite.email,
    inviterEmail: null,
    expired: new Date(invite.expires_at) < new Date(),
    accepted: invite.accepted_at !== null,
  }
}
